//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PowerGuard.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PowerGuard.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محافظ برق - PowerGuard.
        /// </summary>
        internal static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جلوگیری از از دست رفتن داده‌ها در هنگام قطعی برق برنامه‌ریزی شده.
        /// </summary>
        internal static string AppDescription {
            get {
                return ResourceManager.GetString("AppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو خاموشی.
        /// </summary>
        internal static string CancelShutdown {
            get {
                return ResourceManager.GetString("CancelShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای لغو، روی دکمه زیر کلیک کنید.
        /// </summary>
        internal static string ClickToCancelShutdown {
            get {
                return ResourceManager.GetString("ClickToCancelShutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مطمئن هستید که می‌خواهید از برنامه خارج شوید؟ اگر تایمری تنظیم شده باشد، لغو خواهد شد..
        /// </summary>
        internal static string ConfirmExit {
            get {
                return ResourceManager.GetString("ConfirmExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید.
        /// </summary>
        internal static string ConfirmTitle {
            get {
                return ResourceManager.GetString("ConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزانه.
        /// </summary>
        internal static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yyyy/MM/dd HH:mm.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال‌سازی برنامه تکراری.
        /// </summary>
        internal static string EnableRecurring {
            get {
                return ResourceManager.GetString("EnableRecurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال‌سازی یادآوری هوشمند.
        /// </summary>
        internal static string EnableSmartReminders {
            get {
                return ResourceManager.GetString("EnableSmartReminders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان انتخاب شده معتبر نیست..
        /// </summary>
        internal static string ErrorInvalidTime {
            get {
                return ResourceManager.GetString("ErrorInvalidTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموشی سیستم با شکست مواجه شد. لطفاً دستی خاموش کنید..
        /// </summary>
        internal static string ErrorShutdownFailed {
            get {
                return ResourceManager.GetString("ErrorShutdownFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت در استارت‌آپ ویندوز با شکست مواجه شد..
        /// </summary>
        internal static string ErrorStartupRegistration {
            get {
                return ResourceManager.GetString("ErrorStartupRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا.
        /// </summary>
        internal static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جمعه.
        /// </summary>
        internal static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات عمومی.
        /// </summary>
        internal static string GeneralSettings {
            get {
                return ResourceManager.GetString("GeneralSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع کنید.
        /// </summary>
        internal static string GetStarted {
            get {
                return ResourceManager.GetString("GetStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه شروع شد.
        /// </summary>
        internal static string LogAppStarted {
            get {
                return ResourceManager.GetString("LogAppStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه تکراری فعال شد: {0}.
        /// </summary>
        internal static string LogRecurringScheduleActivated {
            get {
                return ResourceManager.GetString("LogRecurringScheduleActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموشی لغو شد.
        /// </summary>
        internal static string LogShutdownCancelled {
            get {
                return ResourceManager.GetString("LogShutdownCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموشی آغاز شد.
        /// </summary>
        internal static string LogShutdownInitiated {
            get {
                return ResourceManager.GetString("LogShutdownInitiated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایمر برای {0} تنظیم شد.
        /// </summary>
        internal static string LogTimerSet {
            get {
                return ResourceManager.GetString("LogTimerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار {0} دقیقه‌ای صادر شد.
        /// </summary>
        internal static string LogWarningIssued {
            get {
                return ResourceManager.GetString("LogWarningIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محافظ برق.
        /// </summary>
        internal static string MainFormTitle {
            get {
                return ResourceManager.GetString("MainFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوشنبه.
        /// </summary>
        internal static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایمری تنظیم نشده است.
        /// </summary>
        internal static string NoTimerSet {
            get {
                return ResourceManager.GetString("NoTimerSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هشدار قطعی برق.
        /// </summary>
        internal static string PowerOutageAlert {
            get {
                return ResourceManager.GetString("PowerOutageAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برنامه‌های تکراری.
        /// </summary>
        internal static string RecurringSchedules {
            get {
                return ResourceManager.GetString("RecurringSchedules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان تکرار:.
        /// </summary>
        internal static string RecurringTime {
            get {
                return ResourceManager.GetString("RecurringTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تکرار:.
        /// </summary>
        internal static string RecurringType {
            get {
                return ResourceManager.GetString("RecurringType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعداً یادآوری کن.
        /// </summary>
        internal static string RemindLater {
            get {
                return ResourceManager.GetString("RemindLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان یادآوری:.
        /// </summary>
        internal static string ReminderTime {
            get {
                return ResourceManager.GetString("ReminderTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شنبه.
        /// </summary>
        internal static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ذخیره.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان قطعی برق را انتخاب کنید:.
        /// </summary>
        internal static string SelectTime {
            get {
                return ResourceManager.GetString("SelectTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اکنون تنظیم کنید.
        /// </summary>
        internal static string SetNow {
            get {
                return ResourceManager.GetString("SetNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیم تایمر خاموشی.
        /// </summary>
        internal static string SetShutdownTimer {
            get {
                return ResourceManager.GetString("SetShutdownTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات محافظ برق.
        /// </summary>
        internal static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایانه شما در {0} دقیقه خاموش خواهد شد. لطفاً کار خود را ذخیره کنید..
        /// </summary>
        internal static string SevenMinuteWarning {
            get {
                return ResourceManager.GetString("SevenMinuteWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش پنجره اصلی.
        /// </summary>
        internal static string ShowMainWindow {
            get {
                return ResourceManager.GetString("ShowMainWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموشی در: {0}.
        /// </summary>
        internal static string ShutdownIn {
            get {
                return ResourceManager.GetString("ShutdownIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال خاموش شدن در {0} ثانیه به دلیل قطعی برق برنامه‌ریزی شده.
        /// </summary>
        internal static string ShutdownInProgress {
            get {
                return ResourceManager.GetString("ShutdownInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خاموشی برنامه‌ریزی شده برای: {0}.
        /// </summary>
        internal static string ShutdownScheduledFor {
            get {
                return ResourceManager.GetString("ShutdownScheduledFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان خاموشی (دقیقه قبل از قطعی):.
        /// </summary>
        internal static string ShutdownTime {
            get {
                return ResourceManager.GetString("ShutdownTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموش نکنید که زمان قطعی برق امروز را تنظیم کنید!.
        /// </summary>
        internal static string SmartReminderMessage {
            get {
                return ResourceManager.GetString("SmartReminderMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یادآوری هوشمند.
        /// </summary>
        internal static string SmartReminderTitle {
            get {
                return ResourceManager.GetString("SmartReminderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع خودکار محافظ برق با ویندوز.
        /// </summary>
        internal static string StartAutomatically {
            get {
                return ResourceManager.GetString("StartAutomatically", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع خودکار با ویندوز.
        /// </summary>
        internal static string StartWithWindows {
            get {
                return ResourceManager.GetString("StartWithWindows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یکشنبه.
        /// </summary>
        internal static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پنج‌شنبه.
        /// </summary>
        internal static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HH:mm.
        /// </summary>
        internal static string TimeFormat {
            get {
                return ResourceManager.GetString("TimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سه‌شنبه.
        /// </summary>
        internal static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان هشدار (دقیقه):.
        /// </summary>
        internal static string WarningTime {
            get {
                return ResourceManager.GetString("WarningTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چهارشنبه.
        /// </summary>
        internal static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزهای هفته:.
        /// </summary>
        internal static string WeeklyDays {
            get {
                return ResourceManager.GetString("WeeklyDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هفتگی.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدید به محافظ برق.
        /// </summary>
        internal static string WelcomeTitle {
            get {
                return ResourceManager.GetString("WelcomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محافظ برق به شما کمک می‌کند تا از از دست رفتن داده‌ها در هنگام قطعی برق برنامه‌ریزی شده جلوگیری کنید. این برنامه هشدارهای به موقع ارائه داده و فرآیند خاموشی سیستم را خودکار می‌کند..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
